dist: trusty
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"

cache:
  directories:
    - $HOME/.cache/pip
    - /home/travis/.sonar/cache

addons:
  sonarqube:
    branches:
      - .*
    token: $SONAR_AUTH_TOKEN
    github_token: $GITHUB_ACCESS_TOKEN

install: "pip install -r requirements/dev.txt"

before_script:
  - chmod +x utils/sonarscript.sh
  - utils/sonarscript.sh
  - python manage.py makemigrations arionBackend && python manage.py migrate

script:
  - python manage.py test arionBackend/tests/

after_success:
  coveralls

notifications:
  email: false
